// Each new term in the Fibonacci sequence is generated by adding
// the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.
public class EulerTwo {
	public static void main(String[] args) {
		int fibValue = 1;
		int oldFibValue = 0;
		int newFibValue = 0;
		int sum = 0;
		while (true) {
			newFibValue = fibValue + oldFibValue;
			if(newFibValue >= 4000000){
				break;
			}
			if(newFibValue % 2 == 0) {
				sum += newFibValue;
			}
			oldFibValue = fibValue;
			fibValue = newFibValue;
		} 
		System.out.println("Solution: " + sum);
	}
}
// Output: 'Solution: 4613732'